name: "JFrog CLI Example"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to artifactory
        env:
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}  # Use secrets to store sensitive data
          JF_URL: ${{ secrets.JF_URL }}
        run: |
          echo "Deploying to artifactory" && curl -L -H "Authorization: Bearer ${{ secrets.JF_ACCESS_TOKEN }}" -T "we_love_text_files.txt" "${JF_URL}/hayden-generic-test/text.txt"

