name: "Jfrog CLI Example"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to artifactory
        env:
          JF_ACCESS_TOKEN: ${{ env.JF_ACCESS_TOKEN }}
	  JF_URL: ${{ env.JF_URL }}
	run: |
	  echo "Deploying to artifactory"
          curl -L -H "Authorization: Bearer $JF_ACCESS_TOKEN" -T we_love_text_files.txt ${JF_URL}/hayden-generic-test/we_love_text_files_art.txt"	
